(function () {
  "use strict";

  const t = (de, en, fr) => ({ de, en, fr });

  const fields = {
    1: t("Selbst & Identität", "Self & identity", "Soi et identité"),
    2: t("Bindung & Beziehung", "Bond & relationship", "Lien et relation"),
    3: t("Begehren & Nähe", "Desire & closeness", "Désir et proximité"),
    4: t("Sicherheit & Zugehörigkeit", "Security & belonging", "Sécurité et appartenance"),
    5: t("Gestaltung & Arbeit", "Creation & work", "Création et travail"),
    6: t("Entscheidung & Bewegung", "Decision & movement", "Décision et mouvement"),
    7: t("Zeit & Wandel", "Time & change", "Temps et changement")
  };

  const positions = [
    { number: 1, title: t("Kern der Frage", "Core of the question", "Cœur de la question"), meaning: t("Das zentrale Thema, um das sich die Legung ordnet.", "The central theme around which the reading takes shape.", "Le thème central autour duquel la lecture s'organise.") },
    { number: 2, title: t("Was sichtbar ist", "What is visible", "Ce qui est visible"), meaning: t("Was bereits erkannt, ausgesprochen oder deutlich wahrnehmbar ist.", "What is already recognized, expressed, or clearly perceptible.", "Ce qui est déjà reconnu, exprimé ou clairement perceptible.") },
    { number: 3, title: t("Was im Verborgenen wirkt", "What works beneath the surface", "Ce qui agit sous la surface"), meaning: t("Ein Gefühl, Bedürfnis oder Einfluss, der noch nicht vollständig benannt ist.", "A feeling, need, or influence that has not yet been fully named.", "Un sentiment, un besoin ou une influence qui n'est pas encore pleinement nommé.") },
    { number: 4, title: t("Was trägt", "What supports", "Ce qui soutient"), meaning: t("Eine vorhandene Kraft, Beziehung oder Erfahrung, die Halt geben kann.", "An existing strength, relationship, or experience that can offer support.", "Une force, une relation ou une expérience qui peut offrir un appui.") },
    { number: 5, title: t("Was belastet", "What weighs on it", "Ce qui pèse"), meaning: t("Eine Spannung, Angst oder Gewohnheit, die Klarheit erschwert.", "A tension, fear, or habit that makes clarity more difficult.", "Une tension, une peur ou une habitude qui rend la clarté plus difficile.") },
    { number: 6, title: t("Was sich bewegt", "What is moving", "Ce qui se met en mouvement"), meaning: t("Die Entwicklung, die bereits begonnen hat oder als Nächstes möglich wird.", "The development that has already begun or may become possible next.", "L'évolution déjà amorcée ou susceptible de devenir possible ensuite.") },
    { number: 7, title: t("Eigene Haltung", "Your own stance", "Votre propre posture"), meaning: t("Wie die fragende Person innerlich auf die Situation antwortet.", "How the person asking is responding inwardly to the situation.", "La manière dont la personne qui questionne répond intérieurement à la situation.") },
    { number: 8, title: t("Einfluss des Umfelds", "Influence of the surroundings", "Influence de l'entourage"), meaning: t("Äußere Bedingungen und das Verhalten anderer, ohne deren Gedanken zu behaupten.", "External conditions and the behavior of others, without claiming to know their thoughts.", "Les conditions extérieures et le comportement d'autrui, sans prétendre connaître ses pensées.") },
    { number: 9, title: t("Hoffnung und Befürchtung", "Hope and concern", "Espoir et crainte"), meaning: t("Was ersehnt wird und wovor zugleich geschützt werden soll.", "What is desired and what one is trying to guard against at the same time.", "Ce qui est désiré et ce contre quoi on cherche en même temps à se protéger.") },
    { number: 10, title: t("Mögliche Richtung", "Possible direction", "Direction possible"), meaning: t("Keine Vorhersage, sondern eine plausible Tendenz und ein nächster verantwortbarer Schritt.", "Not a prediction, but a plausible tendency and a responsible next step.", "Non pas une prédiction, mais une tendance plausible et une prochaine étape responsable.") }
  ];

  const cards = [
    { number: "01", field: 1, title: t("Das verblasste Porträt", "The Faded Portrait", "Le portrait estompé"), meaning: t("Erinnerung und inneres Bild verlieren an Schärfe; Vergangenes und Gegenwärtiges wollen voneinander unterschieden werden.", "A memory or inner image is losing definition; what was and what remains need to be distinguished.", "Un souvenir ou une image intérieure perd de sa netteté; il faut distinguer ce qui était de ce qui demeure."), ask: t("Welches Bild halte ich fest, obwohl es sich verändert hat?", "What image am I holding onto even though it has changed?", "À quelle image est-ce que je m'accroche même si elle a changé?") },
    { number: "02", field: 1, title: t("Der Blick ins Licht", "The Gaze Toward the Light", "Le regard vers la lumière"), meaning: t("Hoffnung richtet die Aufmerksamkeit auf einen möglichen Weg, ohne dessen Ausgang schon zu kennen.", "Hope directs attention toward a possible way forward without knowing its outcome.", "L'espoir dirige l'attention vers une voie possible sans en connaître encore l'issue."), ask: t("Worauf möchte ich meine Aufmerksamkeit bewusst richten?", "Where do I want to direct my attention deliberately?", "Vers quoi est-ce que je veux diriger consciemment mon attention?") },
    { number: "03", field: 1, title: t("Die vertraute Handschrift", "The Familiar Handwriting", "L'écriture familière"), meaning: t("Etwas Bekanntes kehrt wieder: eine Haltung, ein Muster oder eine Stimme, die Sicherheit geben oder Wiederholung anzeigen kann.", "Something familiar returns: an attitude, pattern, or voice that may offer reassurance or signal repetition.", "Quelque chose de familier revient : une attitude, un schéma ou une voix qui peut rassurer ou signaler une répétition."), ask: t("Was erkenne ich wieder – und ist es heute noch hilfreich?", "What do I recognize, and is it still helpful today?", "Qu'est-ce que je reconnais, et est-ce encore utile aujourd'hui?") },
    { number: "04", field: 1, title: t("Das fremde Kleid", "The Unfamiliar Garment", "Le vêtement d'un autre"), meaning: t("Eine Rolle oder Erwartung passt nicht selbstverständlich; Anpassung und Selbstentfremdung müssen unterschieden werden.", "A role or expectation does not fit naturally; adaptation and self-alienation need to be distinguished.", "Un rôle ou une attente ne convient pas naturellement; il faut distinguer l'adaptation de l'éloignement de soi."), ask: t("Was trage ich für andere, obwohl es sich nicht nach mir anfühlt?", "What am I wearing for others even though it does not feel like me?", "Qu'est-ce que je porte pour les autres même si cela ne me ressemble pas?") },
    { number: "05", field: 1, title: t("Die abgelegte Maske", "The Mask Set Aside", "Le masque mis de côté"), meaning: t("Ehrlichkeit und Verletzlichkeit werden möglich, wenn eine schützende Darstellung vorübergehend ruhen darf.", "Honesty and vulnerability become possible when a protective presentation can be set aside for a while.", "L'honnêteté et la vulnérabilité deviennent possibles lorsqu'une façade protectrice peut être déposée un moment."), ask: t("Was würde sichtbar, wenn ich mich nicht erklären oder verteidigen müsste?", "What would become visible if I did not have to explain or defend myself?", "Qu'est-ce qui deviendrait visible si je n'avais pas à me justifier ni à me défendre?") },
    { number: "06", field: 1, title: t("Der verhüllte Spiegel", "The Veiled Mirror", "Le miroir voilé"), meaning: t("Selbstwahrnehmung ist durch Angst, Wunsch oder Projektion verdeckt; Deutungen brauchen Abstand.", "Self-perception is obscured by fear, desire, or projection; interpretation needs distance.", "La perception de soi est voilée par la peur, le désir ou la projection; l'interprétation demande du recul."), ask: t("Was weiß ich wirklich – und was ergänze ich aus Unsicherheit?", "What do I truly know, and what am I adding from uncertainty?", "Qu'est-ce que je sais vraiment, et qu'est-ce que j'ajoute par incertitude?") },
    { number: "07", field: 1, title: t("Die feste Haltung", "The Steady Stance", "La posture ferme"), meaning: t("Innere Ausrichtung und Grenzen geben Halt, solange Standfestigkeit nicht zu Starrheit wird.", "Inner alignment and boundaries provide stability as long as steadiness does not become rigidity.", "L'alignement intérieur et les limites donnent de la stabilité, tant que la fermeté ne devient pas rigidité."), ask: t("Wofür möchte ich ruhig und ohne Härte einstehen?", "What do I want to stand for calmly and without harshness?", "Pour quoi est-ce que je veux tenir bon avec calme, sans dureté?") },

    { number: "08", field: 2, title: t("Der leere Platz", "The Empty Seat", "La place vide"), meaning: t("Abwesenheit, Einsamkeit oder ein unbesetzter Raum wird spürbar und verlangt nach ehrlicher Benennung.", "Absence, loneliness, or an unfilled space becomes noticeable and asks to be named honestly.", "Une absence, une solitude ou une place inoccupée devient sensible et demande à être nommée honnêtement."), ask: t("Was fehlt mir tatsächlich – eine Person, eine Antwort oder ein Gefühl?", "What am I truly missing: a person, an answer, or a feeling?", "Qu'est-ce qui me manque vraiment : une personne, une réponse ou un sentiment?") },
    { number: "09", field: 2, title: t("Das zweite Gedeck", "The Second Place Setting", "Le deuxième couvert"), meaning: t("Bereitschaft für Begegnung und geteilten Raum ist vorhanden; sie ist eine Einladung, keine Garantie.", "There is readiness for connection and shared space; it is an invitation, not a guarantee.", "Une disponibilité à la rencontre et à l'espace partagé est présente; c'est une invitation, non une garantie."), ask: t("Für wen oder was halte ich einen Platz offen?", "For whom or for what am I keeping a place open?", "Pour qui ou pour quoi est-ce que je garde une place ouverte?") },
    { number: "10", field: 2, title: t("Die verflochtenen Zweige", "The Intertwined Branches", "Les branches entrelacées"), meaning: t("Eine Verbindung hat beide Seiten geprägt; Nähe kann tragen, aber auch die eigene Form verändern.", "A connection has shaped both sides; closeness can support, but it can also alter one's own form.", "Un lien a façonné les deux côtés; la proximité peut soutenir, mais aussi modifier sa propre forme."), ask: t("Wo endet Verbundenheit und wo beginnt Verstrickung?", "Where does connection end and entanglement begin?", "Où se termine le lien et où commence l'enchevêtrement?") },
    { number: "11", field: 2, title: t("Das gespannte Seil", "The Taut Rope", "La corde tendue"), meaning: t("Eine Beziehung wird von Spannung, Erwartung oder gegenseitigem Festhalten belastet.", "A relationship is strained by tension, expectation, or mutual holding on.", "Une relation est mise à l'épreuve par la tension, les attentes ou le fait de s'agripper l'un à l'autre."), ask: t("Was würde geschehen, wenn der Zug auf dem Seil nachließe?", "What might happen if the pull on the rope eased?", "Que pourrait-il se passer si la tension sur la corde diminuait?") },
    { number: "12", field: 2, title: t("Die zwei Fahrkarten", "The Two Tickets", "Les deux billets"), meaning: t("Ein gemeinsamer Weg ist denkbar, doch beide Menschen müssen ihn freiwillig wählen.", "A shared journey is conceivable, but both people must choose it freely.", "Un chemin commun est envisageable, mais les deux personnes doivent le choisir librement."), ask: t("Gibt es zwei wirkliche Entscheidungen oder bisher nur einen Wunsch?", "Are there two real decisions, or only one person's wish so far?", "Y a-t-il deux décisions réelles, ou seulement le souhait d'une personne pour l'instant?") },
    { number: "13", field: 2, title: t("Die zurückgezogene Hand", "The Withdrawn Hand", "La main retirée"), meaning: t("Rückzug kann Ablehnung bedeuten, aber ebenso Überforderung, Vorsicht oder Selbstschutz.", "Withdrawal may mean rejection, but it may also mean overwhelm, caution, or self-protection.", "Le retrait peut signifier un refus, mais aussi un débordement, de la prudence ou de l'autoprotection."), ask: t("Kann ich den Rückzug respektieren, ohne seine Ursache zu erfinden?", "Can I respect the withdrawal without inventing its cause?", "Puis-je respecter ce retrait sans en inventer la cause?") },
    { number: "14", field: 2, title: t("Der enge Knoten", "The Tight Knot", "Le nœud serré"), meaning: t("Bindung und Verwicklung liegen nah beieinander; mehr Kraft macht einen Knoten nicht immer lösbarer.", "Commitment and entanglement lie close together; more force does not always loosen a knot.", "L'attachement et l'enchevêtrement sont proches; davantage de force ne défait pas toujours un nœud."), ask: t("Was braucht Geduld, und was braucht behutsames Loslassen?", "What needs patience, and what needs gentle release?", "Qu'est-ce qui demande de la patience, et qu'est-ce qui demande de lâcher doucement?") },

    { number: "15", field: 3, title: t("Die erkaltete Glut", "The Cold Embers", "Les braises refroidies"), meaning: t("Eine frühere Wärme ist schwächer geworden; Erinnerung an Leidenschaft ist nicht dasselbe wie gegenwärtige Nähe.", "Earlier warmth has cooled; the memory of passion is not the same as present closeness.", "Une chaleur passée s'est refroidie; le souvenir de la passion n'est pas la même chose qu'une proximité actuelle."), ask: t("Was ist noch lebendig, und was lebt nur in meiner Erinnerung?", "What is still alive, and what lives only in my memory?", "Qu'est-ce qui est encore vivant, et qu'est-ce qui ne vit que dans mon souvenir?") },
    { number: "16", field: 3, title: t("Der erste Funke", "The First Spark", "La première étincelle"), meaning: t("Neugier, Anziehung oder Begeisterung beginnt; ein Funke kann wachsen, braucht aber Nahrung und Raum.", "Curiosity, attraction, or enthusiasm begins; a spark may grow, but it needs fuel and space.", "La curiosité, l'attirance ou l'enthousiasme commence; une étincelle peut grandir, mais elle a besoin d'espace et de nourriture."), ask: t("Was möchte ich erkunden, ohne es vorschnell festzulegen?", "What do I want to explore without defining it too quickly?", "Qu'est-ce que je veux explorer sans le définir trop vite?") },
    { number: "17", field: 3, title: t("Die vertraute Berührung", "The Familiar Touch", "Le contact familier"), meaning: t("Nähe fühlt sich sicher und bekannt an; Vertrautheit kann Verbundenheit zeigen oder Gewohnheit sein.", "Closeness feels safe and familiar; familiarity may show connection or simply habit.", "La proximité semble sûre et familière; cette familiarité peut témoigner d'un lien ou simplement d'une habitude."), ask: t("Welche Nähe tut mir gut, ohne dass ich mich darin verliere?", "What kind of closeness feels good without making me lose myself?", "Quelle proximité me fait du bien sans que je m'y perde?") },
    { number: "18", field: 3, title: t("Die gespannte Saite", "The Taut String", "La corde sous tension"), meaning: t("Feine Spannung kann Resonanz erzeugen, doch zu viel Druck lässt den Ton kippen oder die Saite reißen.", "Delicate tension can create resonance, but too much pressure can distort the tone or break the string.", "Une tension délicate peut créer une résonance, mais trop de pression peut fausser le son ou rompre la corde."), ask: t("Welche Spannung belebt – und welche überfordert?", "Which tension feels alive, and which becomes too much?", "Quelle tension donne de la vie, et laquelle devient excessive?") },
    { number: "19", field: 3, title: t("Der erste Tanz", "The First Dance", "La première danse"), meaning: t("Annäherung entsteht durch gegenseitiges Wahrnehmen, Tempo und kleine Korrekturen statt durch vollständige Kontrolle.", "Approach grows through mutual attention, timing, and small adjustments rather than complete control.", "Le rapprochement naît de l'attention mutuelle, du rythme et de petits ajustements plutôt que d'un contrôle total."), ask: t("Bewegen wir uns miteinander oder versuche ich, den Takt allein zu bestimmen?", "Are we moving together, or am I trying to set the rhythm alone?", "Est-ce que nous avançons ensemble, ou est-ce que j'essaie d'imposer seul le rythme?") },
    { number: "20", field: 3, title: t("Die abgewandte Schulter", "The Turned Shoulder", "L'épaule tournée"), meaning: t("Distanz wird körperlich oder emotional sichtbar; sie kann Grenze, Müdigkeit oder Schutz ausdrücken.", "Distance becomes physically or emotionally visible; it may express a boundary, fatigue, or protection.", "La distance devient visible physiquement ou émotionnellement; elle peut exprimer une limite, de la fatigue ou une protection."), ask: t("Kann ich Abstand wahrnehmen, ohne ihn sofort als Urteil zu lesen?", "Can I notice distance without immediately reading it as a verdict?", "Puis-je reconnaître la distance sans l'interpréter aussitôt comme un verdict?") },
    { number: "21", field: 3, title: t("Das gebändigte Feuer", "The Tamed Fire", "Le feu maîtrisé"), meaning: t("Starke Energie wird bewusst gehalten; Selbstbeherrschung kann schützen, aber auch Lebendigkeit einschränken.", "Strong energy is being consciously contained; restraint can protect, but it may also limit vitality.", "Une énergie forte est contenue consciemment; la retenue peut protéger, mais aussi limiter l'élan vital."), ask: t("Was darf sicher brennen, ohne außer Kontrolle zu geraten?", "What may burn safely without getting out of control?", "Qu'est-ce qui peut brûler en sécurité sans devenir incontrôlable?") },

    { number: "22", field: 4, title: t("Das erloschene Herdfeuer", "The Extinguished Hearth", "Le foyer éteint"), meaning: t("Wärme, Zuhause oder Zugehörigkeit fehlen; der Verlust will anerkannt werden, bevor Neues entstehen kann.", "Warmth, home, or belonging is missing; the loss needs acknowledgment before something new can grow.", "La chaleur, le foyer ou l'appartenance manquent; la perte doit être reconnue avant qu'un renouveau soit possible."), ask: t("Wo wünsche ich mir Geborgenheit, die derzeit nicht vorhanden ist?", "Where am I longing for a sense of home that is not currently present?", "Où est-ce que je désire un sentiment de sécurité qui n'est pas présent en ce moment?") },
    { number: "23", field: 4, title: t("Das Licht im Fenster", "The Light in the Window", "La lumière à la fenêtre"), meaning: t("Ein Zeichen von Wärme oder Willkommen ist sichtbar; es lädt zur Annäherung ein, ohne Besitz zu versprechen.", "A sign of warmth or welcome is visible; it invites approach without promising belonging.", "Un signe de chaleur ou d'accueil est visible; il invite à s'approcher sans promettre l'appartenance."), ask: t("Welches reale Zeichen von Offenheit kann ich erkennen?", "What real sign of openness can I recognize?", "Quel signe réel d'ouverture puis-je reconnaître?") },
    { number: "24", field: 4, title: t("Die lange Tafel", "The Long Table", "La longue table"), meaning: t("Gemeinschaft, Familie und geteilter Alltag stehen im Mittelpunkt, ebenso die Frage, wer Raum erhält.", "Community, family, and shared daily life take center stage, along with the question of who is given space.", "La communauté, la famille et le quotidien partagé sont au centre, tout comme la question de savoir à qui une place est accordée."), ask: t("An welchem Tisch fühle ich mich willkommen und verantwortlich?", "At what table do I feel both welcome and responsible?", "À quelle table est-ce que je me sens à la fois accueilli et responsable?") },
    { number: "25", field: 4, title: t("Zwei Schlüssel, ein Schloss", "Two Keys, One Lock", "Deux clés, une serrure"), meaning: t("Eine gemeinsame Lösung braucht passende Beiträge beider Seiten; ein Schlüssel allein genügt nicht immer.", "A shared solution requires fitting contributions from both sides; one key alone may not be enough.", "Une solution commune exige une contribution juste des deux côtés; une seule clé ne suffit pas toujours."), ask: t("Was kann nur gemeinsam geöffnet werden?", "What can only be opened together?", "Qu'est-ce qui ne peut être ouvert qu'ensemble?") },
    { number: "26", field: 4, title: t("Das offene Gartentor", "The Open Garden Gate", "Le portail ouvert"), meaning: t("Zugang und Möglichkeit sind vorhanden; Offenheit ist eine Einladung, noch keine Verpflichtung.", "Access and possibility are present; openness is an invitation, not yet a commitment.", "Un accès et une possibilité sont présents; l'ouverture est une invitation, pas encore un engagement."), ask: t("Welche Möglichkeit darf ich betreten, ohne ihren Ausgang zu erzwingen?", "What possibility may I enter without forcing its outcome?", "Dans quelle possibilité puis-je entrer sans en forcer l'issue?") },
    { number: "27", field: 4, title: t("Die verriegelten Läden", "The Locked Shutters", "Les volets verrouillés"), meaning: t("Privatsphäre und Schutz werden verstärkt; von außen lässt sich nicht erzwingen, was innen noch nicht bereit ist.", "Privacy and protection are reinforced; what is not ready inside cannot be forced from outside.", "L'intimité et la protection sont renforcées; on ne peut forcer de l'extérieur ce qui n'est pas prêt à l'intérieur."), ask: t("Welche geschlossene Grenze muss ich respektieren?", "What closed boundary do I need to respect?", "Quelle limite fermée dois-je respecter?") },
    { number: "28", field: 4, title: t("Der hohe Zaun", "The High Fence", "La haute clôture"), meaning: t("Eine starke Grenze schafft Sicherheit, kann aber Austausch und Entwicklung zugleich erschweren.", "A strong boundary creates safety, but it may also make exchange and development harder.", "Une limite forte crée de la sécurité, mais elle peut aussi compliquer l'échange et l'évolution."), ask: t("Schützt mich diese Grenze – oder hält sie auch das Gute fern?", "Is this boundary protecting me, or is it also keeping good things away?", "Cette limite me protège-t-elle, ou éloigne-t-elle aussi ce qui pourrait être bon?") },

    { number: "29", field: 5, title: t("Das unvollendete Werk", "The Unfinished Work", "L'œuvre inachevée"), meaning: t("Ein Prozess ist noch offen und verlangt Geduld, Abschluss oder eine bewusste Entscheidung über seine Fortsetzung.", "A process remains open and calls for patience, completion, or a conscious decision about whether to continue.", "Un processus demeure ouvert et demande de la patience, un achèvement ou une décision consciente quant à sa poursuite."), ask: t("Was ist wirklich noch in Arbeit – und was wurde nur nicht beendet?", "What is truly still in progress, and what was simply left unfinished?", "Qu'est-ce qui est réellement en cours, et qu'est-ce qui a simplement été laissé inachevé?") },
    { number: "30", field: 5, title: t("Der erste Entwurf", "The First Draft", "La première ébauche"), meaning: t("Ein Anfang darf unvollkommen sein; Klarheit entsteht durch Erproben, Prüfen und Überarbeiten.", "A beginning is allowed to be imperfect; clarity grows through trying, reviewing, and revising.", "Un commencement peut être imparfait; la clarté se développe en essayant, en examinant et en révisant."), ask: t("Was darf ich zunächst ausprobieren, statt es sofort perfekt zu machen?", "What may I try first instead of making it perfect immediately?", "Qu'est-ce que je peux d'abord essayer au lieu de vouloir le rendre parfait tout de suite?") },
    { number: "31", field: 5, title: t("Die gemeinsame Werkbank", "The Shared Workbench", "L'établi partagé"), meaning: t("Zusammenarbeit wird praktisch: Beide Seiten bringen Zeit, Fähigkeit und Verantwortung ein.", "Cooperation becomes practical: both sides contribute time, ability, and responsibility.", "La collaboration devient concrète : les deux côtés apportent du temps, des compétences et de la responsabilité."), ask: t("Arbeiten tatsächlich beide am selben Werk?", "Are both sides truly working on the same thing?", "Les deux côtés travaillent-ils réellement au même ouvrage?") },
    { number: "32", field: 5, title: t("Der zerrissene Bauplan", "The Torn Blueprint", "Le plan déchiré"), meaning: t("Ein bisheriger Plan trägt nicht mehr oder wird unterschiedlich verstanden; Neuplanung ist sinnvoller als bloßes Festhalten.", "An earlier plan no longer holds or is understood differently; redesign is wiser than simply holding on.", "Un ancien plan ne tient plus ou n'est pas compris de la même façon; il vaut mieux le repenser que de s'y accrocher."), ask: t("Welcher Plan muss neu gedacht werden, damit Bewegung möglich wird?", "Which plan needs to be rethought so that movement becomes possible?", "Quel plan doit être repensé pour que le mouvement redevienne possible?") },
    { number: "33", field: 5, title: t("Die aufgerollten Ärmel", "The Rolled-Up Sleeves", "Les manches retroussées"), meaning: t("Bereitschaft zum Handeln ist vorhanden; Erkenntnis soll in einen konkreten, überschaubaren Schritt münden.", "Readiness to act is present; insight should lead to a concrete and manageable step.", "La volonté d'agir est présente; la compréhension devrait mener à une étape concrète et réalisable."), ask: t("Was kann ich heute tatsächlich tun?", "What can I genuinely do today?", "Qu'est-ce que je peux réellement faire aujourd'hui?") },
    { number: "34", field: 5, title: t("Die unberührte Leinwand", "The Untouched Canvas", "La toile intacte"), meaning: t("Möglichkeit und Freiheit sind groß, doch der erste Strich verlangt Mut und eine vorläufige Richtung.", "Possibility and freedom are abundant, but the first mark requires courage and a provisional direction.", "Les possibilités et la liberté sont vastes, mais le premier trait demande du courage et une direction provisoire."), ask: t("Welche Möglichkeit bleibt leer, weil ich mich noch nicht festlegen will?", "What possibility remains blank because I do not yet want to commit?", "Quelle possibilité demeure vide parce que je ne veux pas encore m'engager?") },
    { number: "35", field: 5, title: t("Das präzise Uhrwerk", "The Precise Clockwork", "Le mécanisme précis"), meaning: t("Struktur und Verlässlichkeit ermöglichen Fortschritt; zu viel Regelhaftigkeit kann jedoch Lebendigkeit verdrängen.", "Structure and reliability enable progress; too much regulation may crowd out vitality.", "La structure et la fiabilité permettent d'avancer; trop de rigidité peut toutefois étouffer la vitalité."), ask: t("Welche Ordnung hilft – und wo braucht es Spielraum?", "What structure helps, and where is room to move needed?", "Quelle structure aide, et où faut-il laisser de la marge?") },

    { number: "36", field: 6, title: t("Die verpasste Fähre", "The Missed Ferry", "Le traversier manqué"), meaning: t("Ein Zeitpunkt oder eine Gelegenheit ist vorüber; Bedauern darf einer neuen Route Platz machen.", "A moment or opportunity has passed; regret may give way to finding another route.", "Un moment ou une occasion est passé; le regret peut laisser place à la recherche d'une autre route."), ask: t("Welche neue Verbindung wird sichtbar, wenn ich der verpassten nicht nachlaufe?", "What new connection becomes visible when I stop chasing the one I missed?", "Quelle nouvelle voie devient visible si je cesse de courir après celle que j'ai manquée?") },
    { number: "37", field: 6, title: t("Die freie Hand", "The Free Hand", "La main libre"), meaning: t("Spielraum, Fähigkeit und Wahlfreiheit sind vorhanden; Freiheit gewinnt Bedeutung durch bewussten Gebrauch.", "Room, ability, and choice are available; freedom gains meaning through deliberate use.", "De l'espace, des capacités et une liberté de choix sont présents; la liberté prend son sens par un usage conscient."), ask: t("Was kann ich gestalten, weil meine Hand nicht gebunden ist?", "What can I shape because my hand is not tied?", "Qu'est-ce que je peux façonner puisque ma main n'est pas liée?") },
    { number: "38", field: 6, title: t("Das gegebene Wort", "The Promise Given", "La parole donnée"), meaning: t("Verbindlichkeit zeigt sich daran, ob Worte und Handlungen über Zeit miteinander übereinstimmen.", "Commitment is shown by whether words and actions continue to align over time.", "L'engagement se reconnaît à la cohérence entre les paroles et les gestes au fil du temps."), ask: t("Welche Zusage ist durch Verhalten getragen – und welche nur ausgesprochen?", "Which promise is supported by behavior, and which has only been spoken?", "Quelle promesse est soutenue par des gestes, et laquelle n'a été que prononcée?") },
    { number: "39", field: 6, title: t("Die zwei offenen Türen", "The Two Open Doors", "Les deux portes ouvertes"), meaning: t("Mehrere Wege sind möglich; Offenheit befreit, doch eine gelebte Entscheidung verlangt Auswahl.", "Several paths are possible; openness is freeing, but a lived decision requires choosing.", "Plusieurs chemins sont possibles; l'ouverture libère, mais une décision vécue exige un choix."), ask: t("Welche Möglichkeit passt zu meinen Werten, nicht nur zu meiner Angst vor Verlust?", "Which possibility fits my values, not merely my fear of loss?", "Quelle possibilité correspond à mes valeurs, et non seulement à ma peur de perdre?") },
    { number: "40", field: 6, title: t("Der erste Schritt", "The First Step", "Le premier pas"), meaning: t("Eine kleine konkrete Handlung beendet Stillstand, ohne bereits den gesamten Weg festlegen zu müssen.", "One small concrete action ends stagnation without having to determine the entire path.", "Un petit geste concret met fin à l'immobilité sans devoir déterminer tout le chemin."), ask: t("Welcher kleinste ehrliche Schritt ist jetzt möglich?", "What is the smallest honest step possible now?", "Quel est le plus petit pas honnête possible maintenant?") },
    { number: "41", field: 6, title: t("Die Hand an der Klinke", "The Hand on the Handle", "La main sur la poignée"), meaning: t("Eine Schwelle ist erreicht; die Entscheidung ist noch nicht vollzogen, aber unmittelbarer geworden.", "A threshold has been reached; the decision has not yet been made, but it has become immediate.", "Un seuil est atteint; la décision n'est pas encore prise, mais elle est devenue immédiate."), ask: t("Was brauche ich, um die Tür bewusst zu öffnen oder geschlossen zu lassen?", "What do I need in order to open the door deliberately or leave it closed?", "De quoi ai-je besoin pour ouvrir consciemment la porte ou la laisser fermée?") },
    { number: "42", field: 6, title: t("Die straffen Zügel", "The Tight Reins", "Les rênes serrées"), meaning: t("Kontrolle und Disziplin halten die Richtung; ein zu fester Griff kann Vertrauen und Beweglichkeit nehmen.", "Control and discipline maintain direction; too tight a grip can reduce trust and flexibility.", "Le contrôle et la discipline maintiennent la direction; une prise trop serrée peut réduire la confiance et la souplesse."), ask: t("Wo führe ich sinnvoll – und wo versuche ich, Unsicherheit zu beherrschen?", "Where am I guiding wisely, and where am I trying to control uncertainty?", "Où est-ce que je guide avec sagesse, et où est-ce que j'essaie de contrôler l'incertitude?") },

    { number: "43", field: 7, title: t("Die verstummte Glocke", "The Bell Gone Silent", "La cloche devenue muette"), meaning: t("Ein Signal bleibt aus oder wird nicht mehr gehört; Stille kann Verlust, Pause oder notwendiges Zuhören bedeuten.", "A signal is absent or no longer heard; silence may mean loss, pause, or the need to listen.", "Un signal est absent ou n'est plus entendu; le silence peut signifier une perte, une pause ou la nécessité d'écouter."), ask: t("Welche Bedeutung gebe ich der Stille, ohne Gewissheit zu haben?", "What meaning am I giving to silence without certainty?", "Quel sens est-ce que je donne au silence sans avoir de certitude?") },
    { number: "44", field: 7, title: t("Die Kerze vor dem Morgen", "The Candle Before Dawn", "La bougie avant l'aube"), meaning: t("Eine kleine verlässliche Hoffnung trägt durch Ungewissheit; sie ersetzt das Morgen nicht, hilft aber bis dahin.", "A small dependable hope carries one through uncertainty; it does not replace dawn, but it helps until then.", "Un petit espoir fiable aide à traverser l'incertitude; il ne remplace pas l'aube, mais soutient jusque-là."), ask: t("Welches kleine Licht kann ich heute selbst bewahren?", "What small light can I preserve for myself today?", "Quelle petite lumière puis-je moi-même préserver aujourd'hui?") },
    { number: "45", field: 7, title: t("Die Jahresringe", "The Tree Rings", "Les anneaux de croissance"), meaning: t("Entwicklung zeigt sich über Zeit; frühere Jahre bleiben Teil der Geschichte, ohne die Zukunft vollständig festzulegen.", "Growth becomes visible over time; earlier years remain part of the story without fully determining the future.", "La croissance se révèle avec le temps; les années passées font partie de l'histoire sans déterminer entièrement l'avenir."), ask: t("Welche Erfahrung hat mich geprägt, ohne mich festzuschreiben?", "What experience has shaped me without defining me forever?", "Quelle expérience m'a façonné sans me définir pour toujours?") },
    { number: "46", field: 7, title: t("Die gegenläufigen Uhren", "The Clocks at Cross-Purposes", "Les horloges à contretemps"), meaning: t("Menschen oder Vorhaben bewegen sich in unterschiedlichen Rhythmen; Zuneigung allein gleicht Timing nicht automatisch aus.", "People or plans are moving at different rhythms; affection alone does not automatically resolve timing.", "Des personnes ou des projets avancent à des rythmes différents; l'affection seule ne règle pas automatiquement le décalage."), ask: t("Können diese verschiedenen Geschwindigkeiten miteinander vereinbart werden?", "Can these different speeds be brought into agreement?", "Ces rythmes différents peuvent-ils être accordés?") },
    { number: "47", field: 7, title: t("Der abfahrende Zug", "The Departing Train", "Le train qui part"), meaning: t("Ein Übergang ist in Bewegung; Festhalten verhindert die Abfahrt nicht, kann aber den Abschied erschweren.", "A transition is already moving; holding on will not stop departure, but it may make farewell harder.", "Une transition est déjà en mouvement; s'agripper n'empêchera pas le départ, mais peut rendre l'adieu plus difficile."), ask: t("Was muss ich verabschieden, damit ich meinen eigenen Weg sehe?", "What do I need to farewell so that I can see my own path?", "À quoi dois-je dire au revoir pour voir mon propre chemin?") },
    { number: "48", field: 7, title: t("Die Brücke im Dunkeln", "The Bridge in the Dark", "Le pont dans l'obscurité"), meaning: t("Eine Verbindung oder ein Weg ist vorhanden, obwohl nicht jeder Schritt sichtbar ist; Vorsicht und Vertrauen müssen zusammenarbeiten.", "A connection or path exists even though every step is not visible; caution and trust need to work together.", "Un lien ou un chemin existe même si chaque pas n'est pas visible; la prudence et la confiance doivent agir ensemble."), ask: t("Welcher nächste sichere Abschnitt ist erkennbar, auch wenn ich das Ziel noch nicht sehe?", "What next safe section can I see even if the destination remains hidden?", "Quelle prochaine portion sûre puis-je voir même si la destination demeure cachée?") },
    { number: "49", field: 7, title: t("Der festgehaltene Sand", "The Sand Held Tight", "Le sable retenu"), meaning: t("Der Versuch, Wandel vollständig zu kontrollieren, lässt manches erst recht entgleiten; ein lockerer Griff kann bewahren, was wirklich trägt.", "Trying to control change completely can make things slip away faster; a gentler grip may preserve what truly matters.", "Vouloir contrôler entièrement le changement peut faire glisser les choses plus vite; une prise plus douce peut préserver l'essentiel."), ask: t("Was könnte bleiben, wenn ich aufhöre, es krampfhaft festzuhalten?", "What might remain if I stop holding it so tightly?", "Qu'est-ce qui pourrait rester si je cessais de le retenir aussi fortement?") }
  ];

  window.SINNBILD_DATA = Object.freeze({ fields, positions, cards });
}());
